//role
export enum RoleEnum {
  USER = "User",
  ADMIN = "Admin",
  MODERATOR = "Moderator",
  SUPER_ADMIN = "Super_Admin",
}

//status
export enum UserStatusEnum {
  ACTIVE = "Active",
  DEACTIVATED = "Deactivated",
  DELETED = "Deleted",
  BANNED = "Banned",
}

export enum ProviderEnum {
  SYSTEM = "System",
  GOOGLE = "Google",
}

//deactivated reason
export enum DeactivatedReasonEnum {
  FAKE_NAME = "FAKE_NAME",
  COMMUNITY_STANDARDS_VIOLATION = "COMMUNITY_STANDARDS_VIOLATION",
  SPAM_OR_SUSPICIOUS_ACTIVITY = "SPAM_OR_SUSPICIOUS_ACTIVITY",
  FAKE_ACCOUNT = "FAKE_ACCOUNT",
  SCAM_OR_FRAUD = "SCAM_OR_FRAUD",
  COPYRIGHT_VIOLATION = "COPYRIGHT_VIOLATION",
  ILLEGAL_CONTENT = "ILLEGAL_CONTENT",
  SECURITY_ISSUE = "SECURITY_ISSUE",
  UNDERAGE_USER = "UNDERAGE_USER",
  REPEATED_VIOLATIONS = "REPEATED_VIOLATIONS",
  AUTOMATION_ABUSE = "AUTOMATION_ABUSE",
  MISINFORMATION = "MISINFORMATION",
  MARKETPLACE_VIOLATION = "MARKETPLACE_VIOLATION",
  ADS_POLICY_VIOLATION = "ADS_POLICY_VIOLATION",
  IDENTITY_VERIFICATION_FAILED = "IDENTITY_VERIFICATION_FAILED",
  USER_REQUESTED = "USER_REQUESTED",
  OTHER = "OTHER",
}
